before_script:
  - eval $(ssh-agent -s)
  - nvm use 9.11
  - npm install

stages:
  - build
  - release

build-development:
  stage: build  
  except:
    - master
  tags:
    - centos7
  script:
    - npm run build

build-master:
  stage: build
  only:
    - master
  except:
    - tags
  tags:
    - centos7
  script:
    - npm run build
  artifacts:
    when: on_success
    expire_in: 1 hrs
    untracked: true
    paths:
      - src/
      - dist/

release-master:
  stage: release
  only:
    - master
  except:
    - tags
  tags:
    - centos7  
  dependencies:
    - build-master
  before_script:
    - npm install gitlab-ci-releaser
  script:
    - $(npm bin)/gitlab-ci-releaser
    - npm publish
