export const IPC = Object.freeze({
    EVENT_LOG: "EVENT_LOG",
    NETWORK_CHANGE: "NETWORK_CHANGE",
    AO_ETH_RPC_PROMPT: "AO_ETH_RPC_PROMPT",
    AO_ETH_RPC_PROMPT_RESPONSE: "AO_ETH_RPC_PROMPT_RESPONSE"
});
